In [3]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [7]:
toplama = a + b
print("Toplama:\n", toplama)

Toplama:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [9]:
çarpma = a * b
print("Çarpma:\n", çarpma)

Çarpma:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
