In [2]:
import numpy as np

In [3]:
zero_matrix=np.zeros((3, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
ones_matrix=np.ones((3, 3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
ıdentity_matrix=np.eye(3)
ıdentity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
ranged_matrix=np.arange(1, 10)
ranged_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
linear_space_matrix=np.linspace(1, 10, 5)
linear_space_matrix

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])